POST https://<DISCORD_HTML_TRANSCRIPT_HOST>:<DISCORD_HTML_TRANSCRIPT_PORT>/transcript
Server-Version: 0.1.0-beta.6
Authorization: Bearer <DISCORD_HTML_TRANSCRIPT_API_KEY>

# input body
< payload.json

# output and override html file
>>! transcript.html

###

# @no-log
GET https://<DISCORD_HTML_TRANSCRIPT_HOST>:<DISCORD_HTML_TRANSCRIPT_PORT>/health
Server-Version: 0.1.0-beta.6
Authorization: Bearer <DISCORD_HTML_TRANSCRIPT_API_KEY>
