name: Release

on:
  release:
    types: [ published ]

jobs:
  discord-html-transcript-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: central
          server-username: SERVER_USERNAME
          server-password: SERVER_PASSWORD
          gpg-passphrase: GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Publish to Maven Central
        run: mvn deploy -Ppublish -DskipTests -pl core
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  discord-html-transcript-server:
    name: Build ${{ matrix.platform_name }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform_name: "Linux x64"
            suffix: "linux-x86_64"
            extension: ""

          - os: windows-latest
            platform_name: "Windows x64"
            suffix: "windows-x86_64"
            extension: ".exe"

          - os: macos-latest
            platform_name: "macOS ARM64"
            suffix: "darwin-aarch64"
            extension: ""

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Project Version
        shell: bash
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build Native Image
        run: mvn package -Pnative -DskipTests -am -pl server

      - name: Rename Artifact
        shell: bash
        run: |
          ARTIFACT_NAME="discord-html-transcript-server-${{ env.VERSION }}-${{ matrix.suffix }}${{ matrix.extension }}"
          mv "server/target/discord-html-transcript-server${{ matrix.extension }}" "server/target/$ARTIFACT_NAME"
          
          ARTIFACTS="server/target/$ARTIFACT_NAME"
          
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            JAR_PATH="server/target/discord-html-transcript-server-${{ env.VERSION }}.jar"
            ARTIFACTS="$ARTIFACTS,$JAR_PATH"
          fi
          
          echo "RELEASE_ARTIFACTS=$ARTIFACTS" >> $GITHUB_ENV

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.RELEASE_ARTIFACTS }}
